In [1]:
import pandas as pd

In [78]:
data = pd.read_csv('/Volumes/ML_projects/richpeoplecars/NAD_r5_TXT/TXT/NAD_r5.csv', nrows=50000, skiprows=10000000)

/Users/brendanferris/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2714: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [79]:
data

,-1,NJ,BURLINGTON,MOORESTOWN TOWNSHIP,Unnamed: 4,Unnamed: 5,MOORESTOWN,08057,3970,Unnamed: 9,...,18SWK0931327363,{D9E664A9-0CE6-4E2D-BF68-85C33051F214},Unknown,SITE,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,Unnamed: 38,4/15/2016 0:00:00,Unnamed: 40,Unnamed: 41
0,-1,NJ,BURLINGTON,MOORESTOWN TOWNSHIP,NaN,NaN,MOORESTOWN,8057.0,2126.0,NaN,...,18SWK0553226260,{F9409DA6-3CEE-4B3F-BEE2-0D6CACB4E649},Unknown,SITE,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,NaN,4/15/2016 0:00:00,NaN,NaN
1,-1,NJ,BURLINGTON,MOORESTOWN TOWNSHIP,NaN,NaN,NaN,8057.0,NaN,NaN,...,18SWK0234823240,{66586603-A2B5-4075-A9E3-F88F980179C4},Unknown,SITE,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,NaN,4/15/2016 0:00:00,NaN,NaN
2,-1,NJ,BURLINGTON,MOORESTOWN TOWNSHIP,NaN,NaN,MOORESTOWN,8057.0,2361.0,NaN,...,18SWK0380923329,{F7B19D16-92F0-4420-B391-8BD326EDFE34},Unknown,SITE,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,NaN,4/15/2016 0:00:00,NaN,NaN
3,-1,NJ,BURLINGTON,MOORESTOWN TOWNSHIP,NaN,NaN,MOORESTOWN,8057.0,2636.0,NaN,...,18SWK0355322186,{5F6CCC25-EB7B-40E2-B3EF-14D2DF0A32A5},Unknown,SITE,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,NaN,4/15/2016 0:00:00,NaN,NaN
4,-1,NJ,BURLINGTON,LUMBERTON TOWNSHIP,NaN,NaN,LUMBERTON,8048.0,5235.0,NaN,...,18SWK1333322552,{AE8443D7-8825-47C8-9449-E2F6C2B1B830},Unknown,SITE,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,NaN,4/15/2016 0:00:00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,-1,NJ,BURLINGTON,BURLINGTON TOWNSHIP,NaN,NaN,BURLINGTON,8016.0,4282.0,NaN,...,18TWK1567633777,{69AD2D2A-5501-4746-AC64-3C03D6D30EB1},Unknown,PARCEL - CENTROID,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,NaN,4/15/2016 0:00:00,NaN,NaN
49996,-1,NJ,BURLINGTON,CINNAMINSON TOWNSHIP,NaN,NaN,CINNAMINSON,8077.0,3354.0,NaN,...,18SWK0011926969,{03B2D025-6A09-47AB-BA21-F18BA8FC4512},Unknown,PARCEL - CENTROID,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,NaN,4/15/2016 0:00:00,NaN,NaN
49997,-1,NJ,BURLINGTON,BURLINGTON TOWNSHIP,NaN,NaN,BURLINGTON,8016.0,2269.0,NaN,...,18TWK1043133347,{FFDE283F-AE26-4B99-AC20-4B10114CD4E9},Unknown,PARCEL - CENTROID,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,NaN,4/15/2016 0:00:00,NaN,NaN
49998,-1,NJ,BURLINGTON,BURLINGTON TOWNSHIP,NaN,NaN,BURLINGTON,8016.0,4712.0,NaN,...,18TWK1308433540,{34B640F8-9315-42EE-ADD6-9484D31BB026},Unknown,PARCEL - CENTROID,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,NaN,4/15/2016 0:00:00,NaN,NaN
49999,-1,NJ,BURLINGTON,BURLINGTON TOWNSHIP,NaN,NaN,BURLINGTON,8016.0,4709.0,NaN,...,18TWK1324633706,{7F1F6FED-DCD7-4F62-B2B0-2AE94167681C},Unknown,PARCEL - CENTROID,NEW JERSEY OFFICE OF GIS,NJ OFFICE OF GIS,NaN,4/15/2016 0:00:00,NaN,NaN

In [80]:
col = "OID,State,County,Inc_Muni,Uninc_Comm,Nbrhd_Comm,Post_Comm,Zip_Code,Plus_4,Bulk_Zip,Bulk_Plus4,StN_PreMod,StN_PreDir,StN_PreTyp,StN_PreSep,StreetName,StN_PosTyp,StN_PosDir,StN_PosMod,AddNum_Pre,Add_Number,AddNum_Suf,LandmkPart,LandmkName,Building,Floor,Unit,Room,Addtl_Loc,Milepost,Longitude,Latitude,NatGrid_Coord,GUID,Addr_Type,Placement,Source,AddAuth,UniqWithin,LastUpdate,Effective,Expired"
str_col = col.split(',')
data.columns = str_col

In [98]:
subset = data[['State', 'Post_Comm', 'StreetName', 'StN_PosDir', 'Add_Number', 'StN_PosTyp', 'Unit', 'Zip_Code']]

In [99]:
subset.fillna('NULL', inplace=True)

/Users/brendanferris/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/pandas/core/frame.py:4259: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  **kwargs

In [85]:
subset = subset.loc[subset['Post_Comm'] != 'NULL']

In [86]:
subset.to_csv('south_jersey.csv', index=False)

In [100]:
subset.tail(50)

,State,Post_Comm,StreetName,StN_PosDir,Add_Number,StN_PosTyp,Floor,Unit,Room,Zip_Code
49950,NJ,BURLINGTON,LIBERTE,NULL,1233,COURT,NULL,NULL,NULL,8016
49951,NJ,BURLINGTON,KAYE,NULL,1178,COURT,NULL,NULL,NULL,8016
49952,NJ,BORDENTOWN,BIRCH HOLLOW,NULL,267,DRIVE,NULL,NULL,NULL,8505
49953,NJ,BORDENTOWN,BIRCH HOLLOW,NULL,351,DRIVE,NULL,NULL,NULL,8505
49954,NJ,WILLINGBORO,NIAGARA,NULL,35,LANE,NULL,NULL,NULL,8046
49955,NJ,WILLINGBORO,HEATH,NULL,8,LANE,NULL,NULL,NULL,8046
49956,NJ,BORDENTOWN,BIRCH HOLLOW,NULL,211,DRIVE,NULL,NULL,NULL,8505
49957,NJ,BURLINGTON,KAYE,NULL,1126,COURT,NULL,NULL,NULL,8016
49958,NJ,BURLINGTON,KAYE,NULL,1179,COURT,NULL,NULL,NULL,8016
49959,NJ,CHESTERFIELD,YORK,NULL,202,ROAD,NULL,NULL,NULL,8515
49960,NJ,BURLINGTON,LIBERTE,NULL,1237,COURT,NULL,NULL,NULL,8016
49961,NJ,BURLINGTON,LIBERTE,NULL,1226,COURT,NULL,NULL,NULL,8016
49962,NJ,BURLINGTON,LIBERTE,NULL,1204,COURT,NULL,NULL,NULL,8016
49963,NJ,BURLINGTON,LIBERTE,NULL,1240,COURT,NULL,NULL,NULL,8016
49964,NJ,BURLINGTON,LIBERTE,NULL,1214,COURT,NULL,NULL,NULL,8016
49965,NJ,BURLINGTON,LINDSLEY,NULL,404,COURT,NULL,NULL,NULL,8016
49966,NJ,BURLINGTON,KAYE,NULL,1159,COURT,NULL,NULL,NULL,8016
49967,NJ,BURLINGTON,LINDSLEY,NULL,418,COURT,NULL,NULL,NULL,8016
49968,NJ,BURLINGTON,KENNYS,NULL,1415,COVE,NULL,NULL,NULL,8016
49969,NJ,BURLINGTON,130,NULL,1810,NULL,NULL,NULL,NULL,8016
49970,NJ,BURLINGTON,MANOR,NULL,54,DRIVE,NULL,NULL,NULL,8016
49971,NJ,BURLINGTON,MANOR,NULL,3,DRIVE,NULL,NULL,NULL,8016
49972,NJ,BURLINGTON,LINDSLEY,NULL,409,COURT,NULL,NULL,NULL,8016
49973,NJ,MARLTON,DOCK,NULL,230,ROAD,NULL,NULL,NULL,8053
49974,NJ,BURLINGTON,KENNYS,NULL,1412,COVE,NULL,NULL,NULL,8016
49975,NJ,BURLINGTON,LINDSLEY,NULL,417,COURT,NULL,NULL,NULL,8016
49976,NJ,BURLINGTON,MEGANS,NULL,1205,LANE,NULL,NULL,NULL,8016
49977,NJ,BURLINGTON,SUNSET,NULL,1128,ROAD,NULL,NULL,NULL,8016
49978,NJ,BURLINGTON,HENRI,NULL,810,COURT,NULL,NULL,NULL,8016
49979,NJ,BURLINGTON,LINDSLEY,NULL,804,COURT,NULL,NULL,NULL,8016
49980,NJ,BURLINGTON,MEGANS,NULL,1203,LANE,NULL,NULL,NULL,8016
49981,NJ,BURLINGTON,GARNET,NULL,111,DRIVE,NULL,UNIT 1B,NULL,8016
49982,NJ,BURLINGTON,GARNET,NULL,211,DRIVE,NULL,UNIT 2A,NULL,8016
49983,NJ,BURLINGTON,GARNET,NULL,708,DRIVE,NULL,UNIT 7G,NULL,8016
49984,NJ,BURLINGTON,GARNET,NULL,601,DRIVE,NULL,UNIT 6A,NULL,8016
49985,NJ,BURLINGTON,LINDSLEY,NULL,706,COURT,NULL,NULL,NULL,8016
49986,NJ,BORDENTOWN,BIRCH HOLLOW,NULL,348,DRIVE,NULL,NULL,NULL,8505
49987,NJ,LUMBERTON,MAIN,NULL,693,STREET,NULL,NULL,NULL,8048
49988,NJ,BURLINGTON,FAULKNER,NULL,5,COURT,NULL,NULL,NULL,8016
49989,NJ,BURLINGTON,LINDSLEY,NULL,707,COURT,NULL,NULL,NULL,8016
49990,NJ,BURLINGTON,WHISPER,NULL,107,COURT,NULL,NULL,NULL,8016
49991,NJ,BURLINGTON,KYLES,NULL,1011,COVE,NULL,NULL,NULL,8016
49992,NJ,BURLINGTON,GARNET,NULL,1002,DRIVE,NULL,UNIT 10O,NULL,8016
49993,NJ,BURLINGTON,KENNYS,NULL,1419,COVE,NULL,NULL,NULL,8016
49994,NJ,BURLINGTON,LIBERTE,NULL,1211,COURT,NULL,NULL,NULL,8016
49995,NJ,BURLINGTON,LINDSLEY,NULL,708,COURT,NULL,NULL,NULL,8016
49996,NJ,CINNAMINSON,WESTFIELD,NULL,712,DRIVE,NULL,NULL,NULL,8077
49997,NJ,BURLINGTON,KAYE,NULL,1128,COURT,NULL,NULL,NULL,8016
49998,NJ,BURLINGTON,GARNET,NULL,508,DRIVE,NULL,UNIT 5I,NULL,8016
49999,NJ,BURLINGTON,GARNET,NULL,202,DRIVE,NULL,UNIT 2K,NULL,8016

In [101]:
subset['Unit'] = subset['Unit'].str.replace('UNIT', '')

/Users/brendanferris/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [105]:
subset.loc[subset['Room'] != 'NULL']

Empty DataFrame
Columns: [State, Post_Comm, StreetName, StN_PosDir, Add_Number, StN_PosTyp, Floor, Unit, Room, Zip_Code]
Index: []